name: Bump

on:
  workflow_dispatch:
    inputs:
      tap:
      formula:

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{github.event.inputs.tap}}
          formula: ${{github.event.inputs.formula}}
