name: Bump formula

on:
  workflow_dispatch:
    inputs:
      tap:
        default: homebrew/core
      formula:
        required: true
      tag:
      revision:
      livecheck:
        default: true

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: ${{github.event.inputs.formula}} ${{github.event.inputs.tag}}
        run: |
          cat <<-EOS
          tap=${{github.event.inputs.tap}}
          formula=${{github.event.inputs.formula}}
          tag=${{github.event.inputs.tag}}
          revision=${{github.event.inputs.revision}}
          livecheck=${{github.event.inputs.livecheck}}
          EOS

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # Workaround until the `cache` action uses the changes from
      # https://github.com/actions/toolkit/pull/580.
      - name: Unlink workspace
        run: |
          mv "${GITHUB_WORKSPACE}" "${GITHUB_WORKSPACE}-link"
          mkdir "${GITHUB_WORKSPACE}"

      - name: Cache gems
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{steps.set-up-homebrew.outputs.gems-path}}
          key: ${{runner.os}}-rubygems-v2-${{steps.set-up-homebrew.outputs.gems-hash}}
          restore-keys: ${{runner.os}}-rubygems-v2-

      # Workaround until the `cache` action uses the changes from
      # https://github.com/actions/toolkit/pull/580.
      - name: Re-link workspace
        run: |
          rmdir "${GITHUB_WORKSPACE}"
          mv "${GITHUB_WORKSPACE}-link" "${GITHUB_WORKSPACE}"

      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        continue-on-error: false
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{github.event.inputs.tap}}
          formula: ${{github.event.inputs.formula}}
          tag: ${{github.event.inputs.tag}}
          revision: ${{github.event.inputs.revision}}
          livecheck: ${{github.event.inputs.livecheck}}

      # Workaround until the `cache` action uses the changes from
      # https://github.com/actions/toolkit/pull/580.
      - name: Unlink workspace
        if: always()
        run: |
          mv "${GITHUB_WORKSPACE}" "${GITHUB_WORKSPACE}-link"
          mkdir "${GITHUB_WORKSPACE}"
