name: Bump

on:
  schedule:
    # Every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:
    types:
      - bump

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Read formulae
        id: formulae
        uses: juliangruber/read-file-action@v1
        with:
          path: formulae.txt
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          formula: ${{steps.formulae.outputs.content}}
          livecheck: true
