name: Bump cask

on:
  workflow_dispatch:
    inputs:
      tap:
        default: homebrew/cask
      cask:
      version:
      livecheck:
        default: false

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: setup
        uses: Homebrew/actions/setup-homebrew@master
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: ${{steps.setup.outputs.gems-path}}
          key: ${{runner.os}}-rubygems-${{steps.setup.outputs.gems-hash}}
          restore-keys: ${{runner.os}}-rubygems-
      - name: Install gems
        run: brew install-bundler-gems
      - name: Bump casks
        uses: SeekingMeaning/action-homebrew-bump-cask@master
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{github.event.inputs.tap}}
          cask: ${{github.event.inputs.cask}}
          version: ${{github.event.inputs.version}}
          livecheck: ${{github.event.inputs.livecheck}}
