name: Bump

on:
  schedule:
    # At 07:00 UTC every day
    - cron: '0 7 * * *'
  repository_dispatch:
    types:
      - bump

jobs:
  bump:
    strategy:
      matrix:
        formula:
          - pnpm
    continue-on-error: true
    runs-on: macos-latest
    steps:
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          formula: ${{matrix.formula}}
          livecheck: true
