name: Bump formula

on:
  workflow_dispatch:
    inputs:
      tap:
      formula:
      tag:
      revision:
      livecheck:
        default: true

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{github.event.inputs.tap}}
          formula: ${{github.event.inputs.formula}}
          tag: ${{github.event.inputs.tag}}
          revision: ${{github.event.inputs.revision}}
          livecheck: ${{github.event.inputs.livecheck}}
