name: Bump

on:
  push:
    branches:
      - master
  schedule:
    # At 07:00 UTC every day
    - cron: '0 7 * * *'
  repository_dispatch:
    types:
      - bump

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@master
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          formula: pnpm gatsby-cli firebase-cli
          livecheck: true
